export const constants = {
  home: "/",
  collection: "/collection",
  about: "/about",
  contact: "/contact",
  cart: "/cart",
  product: "/product",
  placeOrder: "/place-order",
  orders: "/orders",
  HOME: "HOME",
  COLLECTION: "COLLECTION",
  ABOUT: "ABOUT",
  CONTACT: "CONTACT",
  MyProfile: "My Profile",
  Orders: "Orders",
  Login: "Login",
  Back: "Back",
  OURBESTSELLERS: "OUR BESTSELLERS",
  homeFooter: "Home",
  aboutFooter: "About us",
  DeliveryFooter: "Delivery",
  PrivacyFooter: "Privacy policy",
};
